# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto 0
__all__ = ['HEADER_URLS', 'daisy_styles', 'tailwind_theme_styles', 'scrollspy_style', 'fast_app', 'FastHTML', 'ThemeRadii',
           'ThemeShadows', 'ThemeFont', 'Theme']

# %% ../nbs/01_core.ipynb
import fasthtml.common as fh
from .foundations import *
from fasthtml.common import FastHTML, fast_app
from enum import Enum, auto
from fastcore.all import *
import httpx
from pathlib import Path

# %% ../nbs/01_core.ipynb
@delegates(fh.fast_app, but=['pico'])
def fast_app(*args, pico=False, **kwargs):
    "Create a FastHTML or FastHTMLWithLiveReload app with `bg-background text-foreground` to bodykw for frankenui themes"
    if 'bodykw' not in kwargs: kwargs['bodykw'] = {}
    if 'class' not in kwargs['bodykw']: kwargs['bodykw']['class'] = ''
    kwargs['bodykw']['class'] = stringify((kwargs['bodykw']['class'],'bg-background text-foreground'))
    return fh.fast_app(*args, pico=pico, **kwargs)

# %% ../nbs/01_core.ipynb
@delegates(fh.FastHTML, but=['pico'])
def FastHTML(*args, pico=False, **kwargs):
    "Create a FastHTML app and adds `bg-background text-foreground` to bodykw for frankenui themes"
    if 'bodykw' not in kwargs: kwargs['bodykw'] = {}
    if 'class' not in kwargs['bodykw']: kwargs['bodykw']['class'] = ''
    kwargs['bodykw']['class'] = stringify((kwargs['bodykw']['class'],'bg-background text-foreground'))
    bodykw = kwargs.pop('bodykw',{})
    return fh.FastHTML(*args, pico=pico, **bodykw, **kwargs)

# %% ../nbs/01_core.ipynb
class ThemeRadii(VEnum):
    none = 'uk-radii-none'
    sm = 'uk-radii-sm'
    md = 'uk-radii-md'
    lg = 'uk-radii-lg'

class ThemeShadows:
    none = 'uk-shadows-none'
    sm = 'uk-shadows-sm'
    md = 'uk-shadows-md'
    lg = 'uk-shadows-lg'

class ThemeFont:
    sm = 'uk-font-sm'
    default = 'uk-font-base'

# %% ../nbs/01_core.ipynb
def _headers_theme(color, mode='auto', radii=ThemeRadii.sm, shadows=ThemeShadows.sm, font=ThemeFont.sm):
    return fh.Script(f'''
        const htmlElement = document.documentElement;
        const stored = JSON.parse(localStorage.getItem("__FRANKEN__") || "{{}}");
        const prefersDark = window.matchMedia("(prefers-color-scheme: dark)");
        const configMode = "{mode}" === "auto" ? "system" : "{mode}";
        let modeToUse = stored.mode || (prefersDark.matches ? "dark" : "light");
        if (configMode === "dark" || configMode === "light") modeToUse = configMode;
        if (configMode === "system" && stored.mode) modeToUse = stored.mode;
        const isDark = modeToUse === "dark";
        htmlElement.classList.toggle("dark", isDark);
        htmlElement.dataset.mode = isDark ? "dark" : "light";
        const themeClass = stored.theme || "uk-theme-{color}";
        const radiiClass = stored.radii || "{radii}";
        const shadowClass = stored.shadows || "{shadows}";
        const fontClass = stored.font || "{font}";
        htmlElement.classList.add(themeClass, radiiClass, shadowClass, fontClass);
        htmlElement.dataset.depth = shadowClass.includes("none") ? "flat" : "raised";
    ''')

# %% ../nbs/01_core.ipynb
HEADER_URLS = {
        'franken_css': "https://cdn.jsdelivr.net/npm/franken-ui@2.1.1/dist/css/core.min.css",
        'franken_js_core': "https://cdn.jsdelivr.net/npm/franken-ui@2.1.1/dist/js/core.iife.js",
        'franken_icons': "https://cdn.jsdelivr.net/npm/franken-ui@2.1.1/dist/js/icon.iife.js",
        'tailwind': "https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4",
        'daisyui': """https://cdn.jsdelivr.net/combine/
npm/daisyui@5/base/properties.css,
npm/daisyui@5/base/rootcolor.css,
npm/daisyui@5/base/rootscrollgutter.css,
npm/daisyui@5/base/rootscrolllock.css,
npm/daisyui@5/base/svg.css,
npm/daisyui@5/colors/properties.css,
npm/daisyui@5/colors/properties-extended.css,
npm/daisyui@5/colors/responsive.css,
npm/daisyui@5/colors/responsive-extended.css,
npm/daisyui@5/colors/states.css,
npm/daisyui@5/colors/states-extended.css,
npm/daisyui@5/components/alert.css,
npm/daisyui@5/components/avatar.css,
npm/daisyui@5/components/badge.css,
npm/daisyui@5/components/breadcrumbs.css,
npm/daisyui@5/components/button.css,
npm/daisyui@5/components/calendar.css,
npm/daisyui@5/components/card.css,
npm/daisyui@5/components/carousel.css,
npm/daisyui@5/components/chat.css,
npm/daisyui@5/components/checkbox.css,
npm/daisyui@5/components/collapse.css,
npm/daisyui@5/components/countdown.css,
npm/daisyui@5/components/diff.css,
npm/daisyui@5/components/divider.css,
npm/daisyui@5/components/dock.css,
npm/daisyui@5/components/drawer.css,
npm/daisyui@5/components/dropdown.css,
npm/daisyui@5/components/fab.css,
npm/daisyui@5/components/fieldset.css,
npm/daisyui@5/components/fileinput.css,
npm/daisyui@5/components/filter.css,
npm/daisyui@5/components/footer.css,
npm/daisyui@5/components/hero.css,
npm/daisyui@5/components/hover3d.css,
npm/daisyui@5/components/hovergallery.css,
npm/daisyui@5/components/indicator.css,
npm/daisyui@5/components/input.css,
npm/daisyui@5/components/kbd.css,
npm/daisyui@5/components/label.css,
npm/daisyui@5/components/link.css,
npm/daisyui@5/components/list.css,
npm/daisyui@5/components/loading.css,
npm/daisyui@5/components/mask.css,
npm/daisyui@5/components/menu.css,
npm/daisyui@5/components/mockup.css,
npm/daisyui@5/components/modal.css,
npm/daisyui@5/components/navbar.css,
npm/daisyui@5/components/progress.css,
npm/daisyui@5/components/radialprogress.css,
npm/daisyui@5/components/radio.css,
npm/daisyui@5/components/range.css,
npm/daisyui@5/components/rating.css,
npm/daisyui@5/components/select.css,
npm/daisyui@5/components/skeleton.css,
npm/daisyui@5/components/stack.css,
npm/daisyui@5/components/stat.css,
npm/daisyui@5/components/status.css,
npm/daisyui@5/components/steps.css,
npm/daisyui@5/components/swap.css,
npm/daisyui@5/components/tab.css,
npm/daisyui@5/components/table.css,
npm/daisyui@5/components/textarea.css,
npm/daisyui@5/components/textrotate.css,
npm/daisyui@5/components/timeline.css,
npm/daisyui@5/components/toast.css,
npm/daisyui@5/components/toggle.css,
npm/daisyui@5/components/tooltip.css,
npm/daisyui@5/components/validator.css,
npm/daisyui@5/theme/light.css,
npm/daisyui@5/theme/dark.css,
npm/daisyui@5/utilities/glass.css,
npm/daisyui@5/utilities/join.css,
npm/daisyui@5/utilities/radius.css,
npm/daisyui@5/utilities/typography.css""",
        'apex_charts': "https://cdn.jsdelivr.net/npm/franken-ui@2.1.1/dist/js/chart.iife.js",
        'highlight_js': "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/highlight.min.js",
        'highlight_python': "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/languages/python.min.js",
        'highlight_light_css': "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-light.css",
        'highlight_dark_css': "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build/styles/atom-one-dark.css",
        'highlight_copy': "https://cdn.jsdelivr.net/gh/arronhunt/highlightjs-copy/dist/highlightjs-copy.min.js",
        'highlight_copy_css': "https://cdn.jsdelivr.net/gh/arronhunt/highlightjs-copy/dist/highlightjs-copy.min.css",
}

def _download_resource(url, static_dir):
    "Download a single resource and return its local path"
    static = Path(static_dir)
    fname = static/f"{url[0]}.{'js' if 'js' in url[1] else 'css'}"
    content = httpx.get(url[1], follow_redirects=True).content
    fname.write_bytes(content)
    return (url[0], f"/{static_dir}/{fname.name}")

# %% ../nbs/01_core.ipynb
daisy_styles = Style("""
:root {
  --b1: hsl(var(--background));
  --bc: hsl(var(--background));
  --m: hsl(var(--muted));
  --mc: hsl(var(--muted-foreground));
  --po: hsl(var(--popover));
  --poc: hsl(var(--popover-foreground));
  --b2: hsl(var(--card));
  --b2c: hsl(var(--card-foreground));
  --br: hsl(var(--border));
  --in: hsl(var(--input));
  --p: hsl(var(--primary));
  --pc: hsl(var(--primary-foreground));
  --s: hsl(var(--secondary));
  --sc: hsl(var(--secondary-foreground));
  --a: hsl(var(--accent));
  --ac: hsl(var(--accent-foreground));
  --er: hsl(var(--destructive));
  --erc: hsl(var(--destructive-foreground));
  --b3: hsl(var(--ring));
  --ch1: hsl(var(--chart-1));
  --ch2: hsl(var(--chart-2));
  --ch3: hsl(var(--chart-3));
  --ch4: hsl(var(--chart-4));
  --ch5: hsl(var(--chart-5));
  --rd: var(--radius);
  --color-base-100: hsl(var(--background));
  --color-base-200: hsl(var(--card));
  --color-base-300: hsl(var(--ring));
  --color-base-content: hsl(var(--background));
  --color-primary: hsl(var(--primary));
  --color-primary-content: hsl(var(--primary-foreground));
  --color-secondary: hsl(var(--secondary));
  --color-secondary-content: hsl(var(--secondary-foreground);
  --color-accent: hsl(var(--accent));
  --color-accent-content: hsl(var(--accent-foreground));
  --color-neutral: oklch(20% 0.024 255.701);
  --color-neutral-content: oklch(89.499% 0.011 252.096);
  --color-info: hsl(var(--input));
  --color-info-content: oklch(0% 0 0);
  --color-success: oklch(64.8% 0.15 160);
  --color-success-content: oklch(0% 0 0);
  --color-warning: oklch(84.71% 0.199 83.87);
  --color-warning-content: oklch(0% 0 0);
  --color-error: hsl(var(--destructive));
  --color-error-content: hsl(var(--destructive-foreground));
}
""")

# %% ../nbs/01_core.ipynb
tailwind_theme_styles = Style("""
@theme {
  --font-sans: var(--uk-global-font-family-sans, ui-sans-serif, system-ui, sans-serif);
  --font-mono: var(--uk-global-font-family-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New");

  --color-background: hsl(var(--background));
  --color-foreground: hsl(var(--foreground));
  --color-muted: hsl(var(--muted));
  --color-muted-foreground: hsl(var(--muted-foreground));
  --color-popover: hsl(var(--popover));
  --color-popover-foreground: hsl(var(--popover-foreground));
  --color-card: hsl(var(--card));
  --color-card-foreground: hsl(var(--card-foreground));
  --color-border: hsl(var(--border));
  --color-input: hsl(var(--input));
  --color-primary: hsl(var(--primary));
  --color-primary-foreground: hsl(var(--primary-foreground));
  --color-secondary: hsl(var(--secondary));
  --color-secondary-foreground: hsl(var(--secondary-foreground));
  --color-accent: hsl(var(--accent));
  --color-accent-foreground: hsl(var(--accent-foreground));
  --color-destructive: hsl(var(--destructive));
  --color-destructive-foreground: hsl(var(--destructive-foreground));
  --color-ring: hsl(var(--ring));
  --color-chart-1: hsl(var(--chart-1));
  --color-chart-2: hsl(var(--chart-2));
  --color-chart-3: hsl(var(--chart-3));
  --color-chart-4: hsl(var(--chart-4));
  --color-chart-5: hsl(var(--chart-5));

  --radius-sm: calc(var(--radius, 0.5rem) / 2);
  --radius-md: var(--radius, 0.5rem);
  --radius-lg: calc(var(--radius, 0.5rem) * 1.5);
  --radius-xl: calc(var(--radius, 0.5rem) * 2);

  --shadow-sm: var(--uk-global-shadow-s, 0 1px 2px 0 rgb(0 0 0 / 0.05));
  --shadow-md: var(--uk-global-shadow, 0 4px 6px -1px rgb(0 0 0 / 0.1));
  --shadow-lg: var(--uk-global-shadow, 0 10px 15px -3px rgb(0 0 0 / 0.1));
}
""", type="text/tailwindcss")

# %% ../nbs/01_core.ipynb
scrollspy_style= Style('''
.monster-navbar.navbar-bold a {
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}
.monster-navbar.navbar-bold a.uk-active {
    transform: scale(1.15) ;
    font-weight: bold;
    text-shadow: 0 0 12px rgba(var(--p-rgb), 0.4);
    letter-spacing: 0.02em;
    color: hsl(var(--p) / 1);
}
.monster-navbar.navbar-underline a.uk-active { position: relative; }
.monster-navbar.navbar-underline a.uk-active::after {
    content: '';
    position: absolute;
    left: 0;
    bottom: -2px;
    width: 100%;
    height: 2px;
    background: currentColor;
    animation: slideIn 0.3s ease forwards;
}
@keyframes slideIn {
    from { transform: scaleX(0); }
    to { transform: scaleX(1); }
}
''')

# %% ../nbs/01_core.ipynb
class Theme(Enum):
    "Selector to choose theme and get all headers needed for app.  Includes frankenui + tailwind + daisyui + highlight.js options"
    def _generate_next_value_(name, start, count, last_values): return name
    slate = auto()
    stone = auto()
    gray = auto()
    neutral = auto()
    red = auto()
    rose = auto()
    orange = auto()
    green = auto()
    blue = auto()
    yellow = auto()
    violet = auto()
    zinc = auto()

    def _create_headers(self, urls, mode='auto', icons=True, daisy=True, highlightjs=False, katex=False, apex_charts=False, radii=ThemeRadii.sm, shadows=ThemeShadows.sm, font=ThemeFont.sm):
        "Create header elements with given URLs"
        hdrs = [
            fh.Link(rel="stylesheet", href=urls['franken_css']),
            fh.Script(type="module", src=urls['franken_js_core']),
            fh.Script(src=urls['tailwind']),
            tailwind_theme_styles,
            _headers_theme(self.value, mode=mode, radii=radii, shadows=shadows, font=font),
            scrollspy_style]

        if icons: hdrs.append(fh.Script(type="module", src=urls['franken_icons']))
        if daisy: hdrs += [fh.Link(rel="stylesheet", href=urls['daisyui']), daisy_styles]
        if apex_charts: hdrs += [fh.Script(type='module', src=urls['apex_charts'])]
            
        if highlightjs:
            hdrs += [
                fh.Script(src=urls['highlight_js']),
                fh.Script(src=urls['highlight_python']),
                fh.Link(rel="stylesheet", href=urls['highlight_light_css'], id='hljs-light'),
                fh.Link(rel="stylesheet", href=urls['highlight_dark_css'], id='hljs-dark'),
                fh.Script(src=urls['highlight_copy']),
                fh.Link(rel="stylesheet", href=urls['highlight_copy_css']),
                fh.Script('''
                    hljs.addPlugin(new CopyButtonPlugin());
                    hljs.configure({
                        cssSelector: 'pre code',
                        languages: ['python'],
                        ignoreUnescapedHTML: true
                    });
                    function updateTheme() {
                        const isDark = document.documentElement.classList.contains('dark');
                        document.getElementById('hljs-dark').disabled = !isDark;
                        document.getElementById('hljs-light').disabled = isDark;
                    }
                    new MutationObserver(mutations =>
                        mutations.forEach(m => m.target.tagName === 'HTML' &&
                            m.attributeName === 'class' && updateTheme())
                    ).observe(document.documentElement, { attributes: true });
                    updateTheme();
                    htmx.onLoad(hljs.highlightAll);
                ''', type='module'),
            ]

        if katex:
            hdrs += [
                fh.Link(rel="stylesheet",
                        href="https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css"),
                fh.Script("""
                import katex from 'https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.mjs';
                import autoRender from 'https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/contrib/auto-render.mjs';
                const options = {
                  delimiters: [
                    {left: '$$', right: '$$', display: true},
                    {left: '$', right: '$', display: false}
                  ],
                  ignoredClasses: ['nomath']
                };

                document.addEventListener('htmx:load', evt => {
                  const element = evt.detail.elt || document.body;
                  autoRender(element,options);
                });
                """,type="module"),
                ]
        return hdrs

    def headers(self, mode='auto', icons=True, daisy=True, highlightjs=False, katex=False, apex_charts=False, radii=ThemeRadii.sm, shadows=ThemeShadows.sm, font=ThemeFont.sm ):
        "Create frankenui and tailwind cdns"
        return self._create_headers(HEADER_URLS, mode=mode, icons=icons, daisy=daisy, highlightjs=highlightjs, katex=katex, apex_charts=apex_charts, radii=radii, shadows=shadows, font=font)    
    
    def local_headers(self, mode='auto', static_dir='static', icons=True, daisy=True, highlightjs=False, katex=False, apex_charts=False, radii='md', shadows='sm', font='sm'):
        "Create headers using local files downloaded from CDNs"
        Path(static_dir).mkdir(exist_ok=True)
        local_urls = dict([_download_resource(url, static_dir) for url in HEADER_URLS.items()])
        return self._create_headers(local_urls, mode=mode, icons=icons, daisy=daisy, highlightjs=highlightjs, katex=katex, apex_charts=apex_charts, radii=radii, shadows=shadows, font=font)
